### ISSUE TITLE
Command to dump pdd for the whole file (all functions)

### ISSUE THREAD

**Issue by Maijin** [wargio/r2dec-js#97] opened 2018-09-07 09:31 UTC
Add a command to dump pdd for the whole file (all functions)

**Comment by radare** [comment] 2018-09-07 09:40
pdd @@...

**Comment by Maijin** [comment] 2018-09-07 10:30
Will have duplicate includes

**Comment by brainstorm** [comment] 2018-09-08 10:43
This is a duplicate of issue #95, right?

**Comment by Maijin** [comment] 2019-06-05 12:37
that would be really useful to mass scanning binaries and provide missing opcodes.

**Comment by wargio** [comment] 2019-07-24 11:22
`pddf > /tmp/myfile.c`

**Closed** 2019-07-24 11:21 UTC
Labels: enhancement
