### ISSUE TITLE
String not getting recognized 

### ISSUE THREAD

**Issue by sivaramaaa** [wargio/r2dec-js#131] opened 2018-12-12 14:47 UTC
r2dec was unable to resolve a string  (see the argument to puts)

![screenshot from 2018-12-12 20-11-14](https://user-images.githubusercontent.com/18589720/49877131-bacf8f80-fe4a-11e8-80a5-d922f5602021.png)

While r2 has resolved the string properly !

![screenshot from 2018-12-12 20-11-47](https://user-images.githubusercontent.com/18589720/49877137-c02cda00-fe4a-11e8-92e2-795359296ffe.png)

**Comment by sivaramaaa** [comment] 2018-12-12 14:48
@wargio if u could give me some pointers , i will try to solve this issue :)

**Comment by sivaramaaa** [comment] 2018-12-13 03:22
**no** it's not prsent in izz , i think it's because it's preent in `.rodata` or something ...

![screenshot from 2018-12-13 08-46-30](https://user-images.githubusercontent.com/18589720/49913555-f0f52980-feb3-11e8-9c11-6a2e11804933.png)

afaik r2 doest not depend only on izz rather it tries to decode the address and if it's a valid string it put's them as comment 

imho it would be nice if r2dec also does the same way to decode the address and check if it's a valid string !

**Comment by wargio** [comment] 2018-12-13 08:48
the issue is that i cannot know when a comment is a string or when it is not

**Comment by sivaramaaa** [comment] 2018-12-14 02:52
@wargio yup i understand that , cant we do this from r2dec side , else i can fill an feature request in radare2 issues

**Comment by wargio** [comment] 2018-12-14 08:50
yup

**Comment by wargio** [comment] 2018-12-14 08:52
btw, you can identify the string by decreasing the minimal string search size

**Comment by wargio** [comment] 2019-08-02 14:13
closing this as dup of https://github.com/wargio/r2dec-js/issues/173

**Closed by wargio** 2019-08-02 14:13 UTC
Labels: bug
